### ISSUE TITLE
Gitlab group membership of another group is not taken into account

### ISSUE THREAD

**Issue by nunoalvesmsglife** [explore-dev/semantic-code-reviews-community#11]
**What happened**: Users that have permissions to a given project through a permission given to a group they belong to cannot see that project in ReviewPad

**What you expected to happen**: The project should be visible 😄 

**How to reproduce it (as minimally and precisely as possible)**: 
In Gitlab As user U1 (everything that will be created from here onwards is owned by U1):
- Create group G1
- Add user U2 to G1
- Create group G2
- Add G1 to G2 with Developer role
- Create project G2/P1

In ReviewPad as admin using an access token for U1 add G2/P1

In ReviewPad U2 cannot see G2/P1. 

Going back to GitLab and give direct permission to U2 in G2 (no need to give to P1), delete the project in ReviewPad and add it again it works.

**Anything else we need to know?**:

**Environment**:
- Extension version: 0.19
- Browser & version:
- Others: Gitlab 13.7

**Comment by marcelosousa** [comment]
Thanks for the feedback @nunoalvesmsglife! 
This is likely a bug in the permission system - we'll look into this! 
Can you tell us which [gitlab self-managed tier](https://about.gitlab.com/pricing/self-managed/feature-comparison/) this issue is occurring?

**Comment by nunoalvesmsglife** [comment]
It's the Community Edition, so close to the Core one.

**Comment by Xavier-explore-dev** [comment]
It's also possible that the system did not receive a notification (no webhooks, perhaps). I will check the two scenarios.

**Comment by Xavier-explore-dev** [comment]
As an update, I can confirm that the current gitlab api being used to find the members with access to a group does not detect members invited via groups. We will try to find a work around.

**Comment by Xavier-explore-dev** [comment]
Fix performed. We should deploy it in the next versions as soon as possible.

**Comment by Xavier-explore-dev** [comment]
Fix deployed in version 0.21.
