### ISSUE TITLE
It crashes on a specific PR with `Error on analyzing repository (EX0005)`

### ISSUE THREAD

**Issue by Jolg42** [explore-dev/semantic-code-reviews-community#2]
**What happened**:
<img width="877" alt="Screen Shot 2020-05-19 at 11 35 44" src="https://user-images.githubusercontent.com/1328733/82310608-e69e5f80-99c4-11ea-9611-7d17884aa5f4.png">

**What you expected to happen**:
The expected review UI

**How to reproduce it (as minimally and precisely as possible)**:
Go to https://github.com/prisma/prisma/pull/2311#explore-dev

**Anything else we need to know?**:

**Environment**:
- Extension version: latest v21.2020.01
- Browser & version: latest Chrome 81.0.4044.138 (Official Build) (64-bit)
- Others: macOS

<details>
<summary>Details</summary>

Error on analyzing repository (EX0005)
(╯°□°)╯︵ ┻━┻
Build v21.2020.01

Stacktrace
RequestError: Error trying to get symbols
    at e.<anonymous> (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:90555)
    at l (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:5666)
    at Generator._invoke (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:5419)
    at Generator.forEach.e.<computed> [as next] (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:6023)
    at $t (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:88200)
    at a (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:88404)

Request stack
4ee167f3-0a28-45ab-8796-9c375fcb636e
c6741102-7944-45c9-ae87-d6ea2da39e4a
3ccb9b50-de33-493e-9450-216761d3af42
50f45370-f304-4437-963a-5875bbd9e157
8f20c80f-feab-42f8-83c5-727854d53f5f
7a00c1b8-e892-4a1a-95dc-fa3232e37dba
64e6d9c6-8926-4cc1-b8c9-96a1f3616c74
f32c42bf-f3cf-45d9-996a-e2b677228337

</details>

**Comment by Jolg42** [comment]
It looks like reloading the page made it work 🤷‍♂️

**Comment by ferreiratiago** [comment]
Hi @Jolg42 Thanks for reporting the issue 🙏 Even if an old fashion reloaded solved the problem we will look into the request stack and try to figure out what happened.

**Comment by marcelosousa** [comment]
Hi @Jolg42 , thanks for the feedback! 
We just released a new improved analysis and this issue shouldn't happen anymore. Still, I see that it takes a few seconds to analyze - we'll be rolling more improvements that only analyse the methods that were modified instead of the entire changed file. That should substantially decrease the analysis time. 

Closing for now!

**Comment by Jolg42** [comment]
That was fast! Thanks for the update!
