### ISSUE TITLE
[bug] fails to explore skyra-project/skyra

### ISSUE THREAD

**Issue by favna** [explore-dev/semantic-code-reviews-community#3]
**What happened**:

Trying to use "explore" on this repo: https://github.com/skyra-project/skyra/pull/1004#explore-dev throws an error:
```
Oops! Something bad happened.
Error on analyzing repository (EX0005)
(╯°□°)╯︵ ┻━┻
Build v21.2020.02

Stacktrace
RequestError: Error trying to get symbols
    at e.<anonymous> (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:90555)
    at l (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:5666)
    at Generator._invoke (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:5419)
    at Generator.forEach.e.<computed> [as next] (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:6023)
    at $t (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:88200)
    at a (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:88404)

Request stack
23a24b3f-737e-47e1-8f4c-e965de6c5f31
e71b60ae-b054-408a-a670-2495d78ac9ab
0fa1cd74-4262-4fdb-a56c-d8162a02e248
c591c015-50ef-47b9-bd5f-151f609aecb8
8edf71ad-f701-4537-96e8-fcbbe1d5317d
c52a1db2-2561-40b3-a792-15a23d34d879
467ad600-6c67-41e2-a4c4-03e4df679f94
a09d35fb-d7cd-42b9-8a72-13151b679129
562486a6-daff-4a46-a20e-93b5f59d1a89
If you think this is an issue, please open one here.
```

**What you expected to happen**:

It actually works

**How to reproduce it (as minimally and precisely as possible)**:

- open pull request link
- click explore
- see it error out after a bit

**Anything else we need to know?**:

**Environment**:
- Extension version: v21.2020.02
- Browser & version: Vivaldi 3.0.1874.38 (Stable channel) (64-bit)
- Others:

**Comment by ferreiratiago** [comment]
Hi @Favna 

Thanks for the feedback.

After some investigation we have come to the conclusion that this issue is caused by some performance issues. We are continually working on performance and have released a new version to production which helps solving this problem.

Please git it another try. Thanks.

Closing for now.

**Comment by favna** [comment]
It works now! 
![image](https://user-images.githubusercontent.com/4019718/82729102-026f7180-9cf5-11ea-8ad0-8f77e4d2d9a6.png)

Closing.
