### ISSUE TITLE
[issue]: error when analyzing repository

### ISSUE THREAD

**Issue by zFernand0** [explore-dev/semantic-code-reviews-community#5]
**What happened**:

Received an unexpected error when the extension was analyzing the repository.
https://github.com/zowe/zowe-cli/pull/728#explore-dev

**What you expected to happen**:

Based on the video demonstration on the Chrome Web Store, I expected to the left-right panel distribution with all the references/interfaces outlined in collapsible nodes?

**How to reproduce it (as minimally and precisely as possible)**:

- Go to https://github.com/zowe/zowe-cli/pull/728 
- Click on Explore

**Anything else we need to know?**:

Some thoughts: Maybe a timeout? Maybe exceeded the Public GitHub API Request limit?

**Environment**:
- Extension version: v21.2020.02
- Browser & version: Google Chrome - Version 81.0.4044.113 (Official Build) (64-bit)
- Others:

**Snapshots**:
![image](https://user-images.githubusercontent.com/37381190/83158497-d841f900-a0d2-11ea-9b66-6878ecc4e9b3.png)

**Error Details*:
```
Oops! Something bad happened.
Error on analyzing repository (EX0005)
(╯°□°)╯︵ ┻━┻
Build v21.2020.02

Stacktrace
RequestError: Error trying to get symbols
    at e.<anonymous> (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:90555)
    at l (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:5666)
    at Generator._invoke (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:5419)
    at Generator.forEach.e.<computed> [as next] (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:6023)
    at $t (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:88200)
    at a (chrome-extension://dclabbgfnbmjodobfdhindnleidefmda/app.bundle.js:30:88404)

Request stack
2cfa79d2-73c5-4f27-b550-f3cdc107ad0a
f14db406-9392-4438-8a20-8ad512b17eb0
c642f8e1-9a38-49ed-9c86-71e659a3ab9c
0ff2c126-cfe6-43f8-8ea6-656f62fb78a5
f6d26c54-923a-4257-90ca-4399a8017eb2
c57d1662-df30-43c6-8e42-9e7fe153b8ad
de133e02-1893-4776-a261-3129a0a1e04d
42e33cc2-bcb6-4f48-8131-7b1e51e8e96d
```

**Comment by zFernand0** [comment]
Duplicate of #2 
My apologies!
Reloading works!

**Comment by marcelosousa** [comment]
Thank you for the feedback @zFernand0 ! It does seem be working now - what usually happens is that the first analysis takes longer. We're working testing new improvements that should solve it for most pull requests! :)
