### ISSUE TITLE
Cannot load PR, and it even shows the comments from conversation tab below.

### ISSUE THREAD

**Issue by adrianoapmartins** [explore-dev/semantic-code-reviews-community#6]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Extension version:
- Browser & version:
- Others:

Link: https://github.com/explore-dev/demo-go/pull/5/#explore-dev

![image](https://user-images.githubusercontent.com/38539/83326151-78ca2180-a269-11ea-8cfb-017a50b9da98.png)

**Comment by marcelosousa** [comment]
This is working as intended as it is a go repository.
