### ISSUE TITLE
Analyzing repository: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by ggwpez** [explore-dev/semantic-code-reviews-community#7]
**What happened**: "Something bad"
![Image Pasted at 2020-6-23 18-21](https://user-images.githubusercontent.com/10380170/85429180-a6f80400-b57e-11ea-96da-90c9500c2e7e.png)

**What you expected to happen**: "Something good"

**How to reproduce it (as minimally and precisely as possible)**:  
Using the [web app](https://app.explore.dev/), i entered the pull request `https://github.com/direct-state-transfer/dst-go/pull/50` to try it out, which produced the error shown above.
When: 23.06.2020@16:20UTC.

**Anything else we need to know?**: The chromium-JS console displays these two errors:  
```pre
Access to fetch at 'https://api.explore.dev/pr/symbols?slug=direct-state-transfer/dst-go&baseCommit=a9ec98c11210fed36554bcacbfc2a55b739b41f2&headCommit=a5df51a2c22d0a2c0cda5c45ea71626857e0cbe8' from origin 'https://app.explore.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
```pre
app.97ec0c345873c65f865d.js:40 GET https://api.explore.dev/pr/symbols?slug=direct-state-transfer/dst-go&baseCommit=a9ec98c11210fed36554bcacbfc2a55b739b41f2&headCommit=a5df51a2c22d0a2c0cda5c45ea71626857e0cbe8 net::ERR_FAILED
```
and Firefox:  
```pre
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.explore.dev/pr/symbols?slug=direct-state-transfe…739b41f2&headCommit=a5df51a2c22d0a2c0cda5c45ea71626857e0cbe8. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```
with an [explanatory link](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin).  

**Environment**:
- Extension version: None
- Browser & version: `Chromium 83.0.4103.106` and `Firefox 77.0.1`
- Others:

**Comment by ferreiratiago** [comment]
Hi @ggwpez 

Thanks for the feedback. It looks like we are having some problems analysing some pull requests. We are looking into it.

Let us give you more feedback as soon as we can.

**Comment by ruimiguelsantos** [comment]
Hi @ggwpez , thanks again for taking the time to report this. The underlying issue has been fixed and you should now be able to analyze the PR.

**Comment by ggwpez** [comment]
Yes, thank you @ruimiguelsantos, i already tried it and it seems to work now :raised_hands:.
