### ISSUE TITLE
Code review tab failing

### ISSUE THREAD

**Issue by dysrama** [explore-dev/semantic-code-reviews-community#8]
**What happened**: The explore screen fails

**What you expected to happen**: See the code review page

**How to reproduce it (as minimally and precisely as possible)**: Go to open pull request, click Explore

**Anything else we need to know?**: It fails for all pullrequests, both for our Go repos and React. 
The error is:

v33.2020.01
Stacktrace
TypeError: Failed to fetch

**Environment**:
- Extension version: v33.2020.01
- Browser & version: Chrome Version 85.0.4183.121
- Others:
I allowed the Semantic code reviews app "Read access to code and metadata" and "Read and write access to pull requests" on specified repositories.
Most of the Go repositories point to a private Go repo that I have not allowed access to, but I also tried with a very simple repo that does not include a private repo, and I had the same result.

**Comment by ferreiratiago** [comment]
Hi @dysrama.

Thanks for the feedback.

We will look into the issue and get back to you asap.

**Comment by marcelosousa** [comment]
Hi @dysrama , sorry for the very late response. 

We looked into this issue at the time and couldn't reproduce. 

In the meanwhile, the product evolved quite a bit and the browser extension is currently discontinued.
