### ISSUE TITLE
New Enum literals are not detected as a semantic change

### ISSUE THREAD

**Issue by nunoalvesmsglife** [explore-dev/semantic-code-reviews-community#9]
**What happened**: New literals were added to an Enum, ReviewPad detected no changes to the class

**What you expected to happen**: New literals should be reported as changes done to the class, at least as a new field although they are their own thing. 

**How to reproduce it (as minimally and precisely as possible)**: Having an existing Enum, add a new possibility for that enum 

**Anything else we need to know?**:

**Environment**:
- Extension version: 0.19
- Browser & version: 
- Others:

**Comment by marcelosousa** [comment]
@nunoalvesmsglife thanks for this feedback - we'll get these semantic changes in the upcoming version.
